jobs:
  publish:
    name: upload to PyPI / TestPyPI
    runs-on: ubuntu-latest
    environment: pypi          # if you set an environment in PyPI/TestPyPI UI
    permissions:
      contents: read
      id-token: write          # REQUIRED for Trusted Publishing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: python -m pip install --upgrade build
      - run: python -m build
      - name: Decide index
        id: decide
        run: |
          python - <<'PY'
          import os
          from packaging.version import Version, InvalidVersion
          tag = os.environ['GITHUB_REF_NAME']
          v = tag[1:] if tag.startswith('v') else tag
          try:
              pre = Version(v).is_prerelease or Version(v).is_devrelease
          except InvalidVersion:
              pre = True
          print(f"is_prerelease={str(pre).lower()}")
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write(f"is_prerelease={str(pre).lower()}\n")
          PY
      - name: Publish to TestPyPI (pre/dev)
        if: ${{ steps.decide.outputs.is_prerelease == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish to PyPI (stable)
        if: ${{ steps.decide.outputs.is_prerelease != 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
