name: Publish to PyPI / TestPyPI

on:
  push:
    tags:
      - 'v*'       # e.g. v1.2.3
      - '[0-9]*'   # e.g. 1.2.3
  workflow_dispatch: {}   # allow manual runs

jobs:
  publish:
    name: upload to PyPI / TestPyPI
    runs-on: ubuntu-latest
    # If you set an "environment" in the PyPI/TestPyPI Trusted Publisher, this must match
    # environment: pypi
    permissions:
      contents: read
      id-token: write  # REQUIRED for Trusted Publishing (OIDC)

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: python -m pip install --upgrade build packaging

      - run: python -m build

      - name: Decide index
        id: decide
        run: |
          python - <<'PY'
          import os
          from packaging.version import Version, InvalidVersion
          tag = os.environ['GITHUB_REF_NAME']
          v = tag[1:] if tag.startswith('v') else tag
          try:
              ver = Version(v)
              pre = ver.is_prerelease or ver.is_devrelease
          except InvalidVersion:
              pre = True
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write(f"is_prerelease={str(pre).lower()}\n")
          PY

      - name: Publish to TestPyPI (pre/dev)
        if: ${{ steps.decide.outputs.is_prerelease == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI (stable)
        if: ${{ steps.decide.outputs.is_prerelease != 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
